### ISSUE TITLE
Adicionar suporte a multipastas e multi-idiomas

### ISSUE THREAD

**Issue by gusbemacbe** [btd1337/icons-missing-script#1]
Olá @btd1337 !

Sou colaborador do GNOME++.

Não se limite apenas ao `/usr/share/applications`.

Seu executável também deve buscar os seguintes:

* `~/.local/share/applications`
* `~/.local/share/flaptak/app`
* `/var/lib/snapd/desktop/applications/*.desktop`

Caso queira fazer pedidos de ícones perdidos ao Andrea Bonanni (Bonandry ou Magog64, autor do GNOME++), lembre-se que ele não é fluente em inglês, por isso, inclua Name[it] e Comment[it], caso os arquivos tenham. Observe que Andrea não é um analista nem programador. Ele é apenas um designer.

**Comment by btd1337** [comment]
@gusbemacbe Em breve vou melhorar o script e incluir este suporte.

**Comment by btd1337** [comment]
https://github.com/btd1337/icons-missing-script/commit/387631201364a23a96b08128538c0daa5a74914d

**Comment by gusbemacbe** [comment]
@btd1337 

https://github.com/btd1337/icons-missing-script/blob/387631201364a23a96b08128538c0daa5a74914d/identify-missing-icons.sh#L33-L36

Adicione algo:

```bash
 appname=$(sed -n '/^Name=/p; /^Name=/q' $entry) 
 appname="${appname#"Name="}" 
 appnameit=$(sed -n '/^Name[it]=/p; /^Name[it]=/q' $entry) 
 appnameit="${appname#"Name[it]="}" 
 echo "- [ ] **$appname**" >> $dest_file
 echo "- [ ] **$appnameit**" >> $dest_file 
 sed -n '/^Comment=/p; /^Comment=/q' $entry >> $dest_file 
 sed -n '/^Comment[it]=/p; /^Comment[it]=/q' $entry >> $dest_file 
```

Porque Andrea não é fluente em inglês.

**Comment by btd1337** [comment]
Resolvido em: https://github.com/btd1337/icons-missing-script/commit/387631201364a23a96b08128538c0daa5a74914d e https://github.com/btd1337/icons-missing-script/commit/07a16edd740dc2244cf18de757acc672ab76846a

**Comment by btd1337** [comment]
@gusbemacbe Se quiser, pode citar este projeto na documentação do Gnome++, usando-o como referência para novas solicitações.
