### ISSUE TITLE
Qual o aplicativo posso visualizar o ficheiro Main?

### ISSUE THREAD

**Issue by gusbemacbe** [btd1337/icons-missing-script#2]
No terminal, posso visualizá-lo, mas quero visualizar no editor de texto.

Eu peguei os ícones perdidos de Linux Mint no tópico de @Baemir na referência do repositório https://github.com/Bonandry/yaru-plus/issues/37.

Mas o ficheiro `Main` mostrou a lista de ícones que eram teus e não eram do LInux Mint.

**Comment by btd1337** [comment]
Este programa retorna apenas a URL dos ícones que já tenham sido cadastrados.

Se eu precisar do link para algum ícone que eu já tenha cadastrado, ele me retorna e dessa forma eu não preciso ficar procurando repetidamente.

**Comment by gusbemacbe** [comment]
@btd1337 

![image](https://user-images.githubusercontent.com/2257024/69155518-a36c3e00-0ac0-11ea-9b3a-0f2af735a6a1.png)

**Comment by btd1337** [comment]
O que deseja fazer?

**Comment by gusbemacbe** [comment]
Quero que o ficheiro `Main` mostre todos os ícones perdidos do meu Linux Mint e não os do teu Arch. Sei do ficheiro `my_request.txt`.

**Comment by btd1337** [comment]
Ele não tem essa função. Ele é apenas um visualizador de um banco de dados SQLite que salva o endereço URL de ícones que eu vou adicionando a medida que preciso.

Quem gera o arquivo `my_request.txt` é o script `identify-missing-icons.sh`.

**Comment by gusbemacbe** [comment]
@btd1337 

Entendi agora! Obrigado pela explanação!
